#%RAML 1.0 SecurityScheme
type: x-client-enforcement
describedBy:
  headers:
    client_id:
      type: string
      required: true
      example: 1a3rfe496jfkms49402srr93
    client_secret:
      type: string
      required: true
      example: 7o9der492wklsmnxcvrt48f1
  responses:
    401:
      description:
      body:
        application/json:
          type: !include ../datatypes/responses/errors/error-type.raml
          example: !include ../examples/responses/error/unauthorized.json