#%RAML 1.0 SecurityScheme
type: Digest Authentication
description: This API supports DigestSecurityScheme Authentication.

describedBy:
  responses:
    401:
      description: 
      body:
        application/json:
          type: !include ../datatypes/responses/errors/error-type.raml
          example: !include ../examples/responses/error/unauthorized.json
    403:
      description:
      body:
        application/json:
          type: !include ../datatypes/responses/errors/error-type.raml
          example: !include ../examples/responses/error/forbidden.json