#%RAML 1.0 SecurityScheme
type: OAuth 1.0
settings:
  requestTokenUri: https://api.mysampleapi.com/1/oauth/request_token
  authorizationUri: https://api.mysampleapi.com/1/oauth/authorize
  tokenCredentialsUri: https://api.mysampleapi.com/1/oauth/access_token
  signatures: [ 'HMAC-SHA1', 'PLAINTEXT' ]

describedBy:
  responses:
    401:
      description: 
      body:
        application/json:
          type: !include ../datatypes/responses/errors/error-type.raml
          example: !include ../examples/responses/error/unauthorized.json
    403:
      description: 
      body:
        application/json:
          type: !include ../datatypes/responses/errors/error-type.raml
          example: !include ../examples/responses/error/forbidden.json