#%RAML 1.0 SecurityScheme
type: Pass Through
description: This API supports Pass Through Authentication.
describedBy:
  headers:
    api_key:
      type: string
  queryParameters:
    query:
      type: string
  responses:
    401:
      description: 
      body:
        application/json:
          type: !include ../datatypes/responses/errors/error-type.raml
          example: !include ../examples/responses/error/unauthorized.json