#%RAML 1.0 Library

usage: Common RAML Fragments to standardise implementation of common aspects of RAML API Specifications.

securitySchemes:
  clientEnforcement: !include securitySchemes/clientEnforcement.raml
  basicAuthentication: !include securitySchemes/basicAuthentication.raml
  digestAuthentication: !include securitySchemes/digestAuthentication.raml
  oAuth1.0: !include securitySchemes/oAuth1.0.raml
  oAuth2.0: !include securitySchemes/oAuth2.0.raml
  passThrough: !include securitySchemes/passThrough.raml
  anotherAuthentication: !include securitySchemes/anotherAuthentication.raml